config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope controller: :application do
    get :build_id, constraints: { format: :json }, defaults: { format: :json }
    get :health, constraints: { format: :json }, defaults: { format: :json }
  end

  devise_for :users, controllers: { sessions: 'sessions' }

  constraints(CheckRequestFormat) do
    authenticated(:user) { root 'upload#index', as: :authenticated_root }
    devise_scope(:user) { root to: 'devise/sessions#new' }

    resources :vehicles, only: %i[index] do
      collection do
        get :search
        post :search, to: 'vehicles#submit_search'
        get :historic_search
        get :not_found
      end
    end

    resources :upload, only: %i[] do
      collection do
        post :import
        get :processing
        get :success
        get :data_rules
      end
    end

    resources :la_request, only: %i[index] do
      collection do
        post :index, to: 'la_request#submit_la_request'
        get :review
        post :review, to: 'la_request#submit_review'
      end
    end

    resources :passwords, only: %i[new create] do
      collection do
        get '/', to: redirect('/')
        get :success
        get :reset
        get :email_send
        get :invalid_or_expired
        post :submit_reset_your_password
        get :confirm_reset
        post :change
      end
    end

    scope controller: 'static_pages' do
      get :accessibility_statement
      get :cookies
      get :privacy_notice
    end

    scope controller: 'errors' do
      get :service_unavailable
    end

    match '/404', to: 'errors#not_found', via: :all
    match '/422', to: 'errors#internal_server_error', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all
    match '/503', to: 'errors#service_unavailable', via: :all
  end
  match '*unmatched', to: 'errors#not_found', via: :all
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

##
# Controller class for the static pages
#
class StaticPagesController < ApplicationController
  # clear the request_form session
  before_action :clear_request_form_session

  ##
  # Renders the accessibility statement page
  #
  # ==== Path
  #    GET /accessibility_statement
  #
  def accessibility_statement
    # renders static page
  end

  ##
  # Renders the cookies page
  #
  # ==== Path
  #    GET /cookies
  #
  def cookies
    # renders static page
  end

  ##
  # Renders the privacy notice page
  #
  # ==== Path
  #    GET /privacy_notice
  #
  def privacy_notice
    # renders static page
  end
end

app/views/static_pages/accessibility_statement.html.haml
- title_and_header = 'Accessibility statement for Centralised Taxi and Private Hire Vehicle Database'
- content_for(:title, title_and_header)

= render 'shared/js_back_link'

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      %h1.govuk-heading-xl
        = title_and_header
      %p
        This website is run by the Joint Air Quality Unit (JAQU) supported by the Department of
        Transport and Department for Environment, Food and Rural Affairs. We want as many people as
        possible to be able to use this website.
      %p
        For example, that means you should be able to:
        %ul.govuk-list-govuk-list--bullet
          %li
            %p
              zoom in up to 300% without the text spilling off the screen.
          %li
            %p
              navigate most of the website using just a keyboard.
          %li
            %p
              navigate most of the website using speech recognition software.
          %li
            %p
              listen to most of the website using a screen reader (including the most recent
              versions of JAWS, NVDA and VoiceOver).
      %p We've also made the website text as simple as possible to understand.
      %p
        = external_link_to('AbilityNet',
                           'https://mcmw.abilitynet.org.uk/',
                           id: 'ability-net-link')
        has advice on making your device easier to use if you have a disability.

      %h2.govuk-heading-m Reporting accessibility problems with this website
      %p
        We're always looking to improve the accessibility of this website. If you find any problems
        that are not listed on this page or think we're not meeting accessibility requirements,
        let us know by emailing us at:
        = mail_to('TaxiPHVDatabase.Support@informed.com',
                           'TaxiPHVDatabase.Support@informed.com',
                           id: 'mail_to_address')

      %h2.govuk-heading-m Enforcement procedure
      %p
        The Equality and Human Rights Commission (EHRC) is responsible for enforcing the Public
        Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018
        (the 'accessibility regulations'). If you're not happy with how we respond to your
        complaint,
        = succeed '.' do
          = external_link_to('contact the Equality Advisory and Support Service (EASS)',
                             'https://www.equalityadvisoryservice.com/',
                             id: 'eass-link')

      %h2.govuk-heading-m Technical information about this website's accessibility
      %p
        JAQU is committed to making its website accessible, in accordance with the Public Sector
        Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018.
      %p
        This website is compliant with the
        = external_link_to('Web Content Accessibility Guidelines version 2.1',
                           'https://www.w3.org/TR/WCAG21/',
                           id: 'guidelines-link')
        AA standard.

      %h2.govuk-heading-m How we tested this website
      %p
        This website is tested regularly with
        = external_link_to('https://pa11y.org/',
                           'https://pa11y.org/',
                           id: 'pa11y-url')
        tools by the team that maintains it, and periodically by external bodies.
      %p We test all routes through the service
      %p This statement was prepared on 16 January 2020.

app/views/static_pages/cookies.html.haml
- title_and_header = 'Cookies'
- content_for(:title, title_and_header)

= render 'shared/js_back_link'

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      = render 'static_pages/cookies/cookies_settings_notification'

      %h1.govuk-heading-xl= title_and_header
      %p
        A cookie is a small piece of data that’s stored on your computer, tablet, or phone when you
        visit a website. Most websites need cookies to work properly.
      %p How cookies are used in this service:
      %ul.govuk-list-govuk-list--bullet
        %li
          %p measure how you use the service so it can be improved
        %li
          %p temporarily store the answers you give
      %p
        Find out more about
        = succeed '.' do
          = external_link_to('how to manage cookies', 'https://www.aboutcookies.org', id: 'manage-cookies-link')
      .cookie-settings-wrapper
        = render 'static_pages/cookies/ga'
        = render 'static_pages/cookies/session'
        = render 'static_pages/cookies/cookies_settings'

      .cookie-settings-wrapper-no-js
        %h2.govuk-heading-m Cookie settings
        %p
          We use Javascript to set most of our cookies. Unfortunately Javascript is not running on your browser, so you
          cannot change your settings. You can try:
          %ul.govuk-list-govuk-list--bullet
            %li
              %p reloading the page
            %li
              %p turning on Javascript in your browser

app/views/static_pages/privacy_notice.html.haml
- title_and_header = 'Privacy Notice'
- content_for(:title, title_and_header)

= render 'shared/js_back_link'

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      %h1.govuk-heading-xl
        = title_and_header
      %p
        = succeed '.' do 
          = external_link_to('Details of our Personal Information Charter',
                             'https://www.gov.uk/government/organisations/department-for-environment-food-rural-affairs/about/personal-information-charter',
                             id: 'personal_information_charter_url')

      %h2.govuk-heading-m 1. Who is collecting the data?
      %p The data will be collected by Defra.
      %p You can contact the Defra data protection officer by:
      %ul.govuk-list-govuk-list--bullet
        %li
          %p
            writing to us: Data Protection Manager for core-Defra
            %br
            Defra
            %br
            Information Rights Team
            %br
            Area 1E
            %br
            Nobel House
            %br
            17 Smith Square
            %br
            London
            %br
            SW1P 3JR
        %li
          %p
            Email:
            = mail_to 'data.protection@defra.gov.uk'

      %h2.govuk-heading-m 2. Purpose of the processing and the legal basis for the processing
      %p
        The Department for Environment Food & Rural Affairs (Defra), which is a government
        department, is collecting data from licensing authorities in England and Wales for all
        vehicles licensed as a taxi or private hire vehicle. Under the Air Quality (Taxi and
        Private Hire Vehicles Database) (England and Wales) Regulations 2019 (SI 2019 No. 885) it
        is a legal obligation for licensing authorities to provide Defra with the following data:
      %ul.govuk-list-govuk-list--bullet
        %li
          %p Vehicle registration mark of the vehicle
        %li
          %p Date from which the vehicle’s licence has effect
        %li
          %p Date on which the vehicle’s licence is due to expire
        %li
          %p A statement as to whether the vehicle is a taxi or private hire vehicle
        %li
          %p
            Other information the licensing authority holds in relation to the vehicle that may be
            relevant for the purposes of ensuring the accurate identification of vehicles, having
            had regard to any guidance issued by the Secretary of State. That is:
          %ul.govuk-list-govuk-list--bullet
            %li
              %p Licence plate number
            %li
              %p An indication as to whether it is a wheelchair accessible vehicle.
      %p
        The Licensing Authorities will provide Defra with this information at least as frequently as
        once a week.
      %p
        The processing of the information (under Article 6.1 (c) of the GDPR) is for the purpose of
        ensuring that Clean Air Zone (CAZ) charging is applied correctly in adherence with the
        = succeed '.' do 
          = external_link_to('Clean Air Zone Framework',
                             'https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/612592/clean-air-zone-framework.pdf',
                             id: 'caz_framework_url')
        Licensing authorities hold information on taxis and PHVs only within
        their own area so are not able to clearly identify and charge a taxi/PHV entering or moving
        around their charging CAZ which has been licensed by another authority (also known as ‘out
        of area vehicles’). If local authorities cannot identify all out of area vehicles this would
        undermine their ability to effectively operate CAZs where charging of these vehicles has
        been determined to be necessary.
      %h2.govuk-heading-m 3. Any recipient or categories of recipients of the personal data
      %p
        The Air Quality (Taxi and Private Hire Vehicles Database) (England and Wales) Regulations
        2019 (2019 SI No. 885) allow the sharing of data received with licensing authorities for the
        purposes of enforcing measures which have been implemented in an air quality plan or for the
        purposes of improving air quality.
      %p
        Defra may, under contracts or similar agreements, use third party organisations to process
        your personal data in connection with the purpose described at ‘2’ above.
        These organisations will not be able to use your data for any other purpose and will be
        required to meet the requirements of data protection legislation and government’s security
        standards.

      %h2.govuk-heading-m 4. Retention period or criteria used to determine the retention period
      %p
        Your personal data will be kept by Defra for as long as is necessary up to seven years,
        in line with the Memorandum of Understanding between Defra and licensing authorities.

      %h2.govuk-heading-m 5. Details of transfers to third country and safeguards
      %p
        The data you provide will not be transferred outside the United Kingdom.

      %h2.govuk-heading-m 6. The existence of each of data subject’s rights.
      %p
        Your rights under the
        = succeed '.' do 
          = external_link_to('General Data Protection Regulation and the Data Protection Act 2018 (DPA 2018)',
                             'https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/',
                             id: 'individual_rights_url')

      %h2.govuk-heading-m
        7. The right to lodge a complaint with a supervisory authority.
      %p
        The Personal Information Charter provides details of
        = succeed '.' do 
          = external_link_to('how to complain',
                             'https://www.gov.uk/government/organisations/department-for-environment-food-rural-affairs/about/personal-information-charter',
                             id: 'how_to_complain_url')

      %h2.govuk-heading-m
        Support links
      %ul.govuk-list-govuk-list--bullet
        %li
          %p
            = link_to 'Cookies', cookies_path, class: 'govuk-link', id: 'cookies-link'
        %li
          %p
            = link_to 'Privacy', privacy_notice_path, class: 'govuk-link', id: 'privacy-link'

app/views/static_pages/privacy_policy.html.haml
%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      %h1.govuk-heading-xl
        Privacy Notice
      %p
        = link_to 'Details of our Personal Information Charter',
                  'https://www.gov.uk/government/organisations/department-for-environment-food-rural-affairs/about/personal-information-charter',
                  target: '_blank'

      %h2.govuk-heading-m 1. Who is collecting the data?
      %p The data will be collected by Defra.
      %p You can contact the Defra data protection officer by:
      %ul.govuk-list-govuk-list--bullet
        %li
          %p
            writing to us: Data Protection Manager for core-Defra
            %br
            Defra
            %br
            Information Rights Team
            %br
            Area 1E
            %br
            Nobel House
            %br
            17 Smith Square
            %br
            London
            %br
            SW1P 3JR
        %li
          %p
            Email:
            = mail_to 'data.protection@defra.gov.uk'

      %h2.govuk-heading-m 2. Purpose of the processing and the legal basis for the processing
      %p
        The Department for Environment Food & Rural Affairs (Defra), which is a government
        department, is collecting data from licensing authorities in England and Wales for all
        vehicles licensed as a taxi or private hire vehicle. Under the Air Quality (Taxi and
        Private Hire Vehicles Database) (England and Wales) Regulations 2019 (SI 2019 No. 885) it
        is a legal obligation for licensing authorities to provide Defra with the following data:
      %ul.govuk-list-govuk-list--bullet
        %li
          %p Vehicle registration mark of the vehicle
        %li
          %p Date from which the vehicle’s licence has effect
        %li
          %p Date on which the vehicle’s licence is due to expire
        %li
          %p A statement as to whether the vehicle is a taxi or private hire vehicle
        %li
          %p
            Other information the licensing authority holds in relation to the vehicle that may be
            relevant for the purposes of ensuring the accurate identification of vehicles, having
            had regard to any guidance issued by the Secretary of State. That is:
          %ul.govuk-list-govuk-list--bullet
            %li
              %p Licence plate number
            %li
              %p An indication as to whether it is a wheelchair accessible vehicle.
      %p
        The Licensing Authorities will provide Defra with this information at least as frequently as
        once a week. The information will be held securely by Defra on Amazon Web Services for up to
        seven years.
      %p
        The processing of the information (under Article 6.1 (c) of the GDPR) is for the purpose of
        ensuring that Clean Air Zone (CAZ) charging is applied correctly in adherence with the
        = link_to 'Clean Air Zone Framework.',
                  'https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/612592/clean-air-zone-framework.pdf',
                  target: '_blank'
        Licensing authorities hold information on taxis and PHVs only within
        their own area so are not able to clearly identify and charge a taxi/PHV entering or moving
        around their charging CAZ which has been licensed by another authority (also known as ‘out
        of area vehicles’). If local authorities cannot identify all out of area vehicles this would
        undermine their ability to effectively operate CAZs where charging of these vehicles has
        been determined to be necessary.
      %h2.govuk-heading-m 3. Any recipient or categories of recipients of the personal data
      %p
        The Air Quality (Taxi and Private Hire Vehicles Database) (England and Wales) Regulations
        2019 (2019 SI No. 885) allow the sharing of data with licensing authorities for the purposes
        of enforcing measures which have been implemented in an air quality plan or for the purposes
        of improving air quality.

      %h2.govuk-heading-m 4. The right to withdraw consent at any time, where relevant
      %p
        See the
        = link_to 'Personal Information Charter',
                  'https://www.gov.uk/government/organisations/department-for-environment-food-rural-affairs/about/personal-information-charter',
                  target: '_blank'

      %h2.govuk-heading-m 5. Retention period or criteria used to determine the retention period
      %p
        Your personal data will be kept by us for as long as is necessary up to seven years, in line
        with the Memorandum of Understanding between Defra and licensing authorities.

      %h2.govuk-heading-m
        6. The existence of automated decision making, including profiling and
        information about how decisions are made, the significance and the consequences.
      %p
        The information you provide is connected with individual decision making (making a decision
        solely by automated means without any human involvement) through the Clean Air Zone vehicle
        checker which determines whether a vehicle entering a charging zone is chargeable.

      %h2.govuk-heading-m 7. Details of transfers to third country and safeguards
      %p
        The data you provide will not be transferred outside the United Kingdom.

      %h2.govuk-heading-m 8. The existence of each of data subject’s rights.
      %p
        You rights under the
        = link_to 'General Data Protection Regulation, the Data Protection Act2018 (DPA 2018)',
                  'https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/',
                  target: '_blank'

      %h2.govuk-heading-m
        9. The right to lodge a complaint with a supervisory authority.
        [How do I complain?]
      %p
        The Personal Information Charter provides details of
        = link_to 'how to complain',
                  'https://www.gov.uk/government/organisations/department-for-environment-food-rural-affairs/about/personal-information-charter',
                  target: '_blank'